OpenOrbis/OpenOrbis-PS4-Toolchain

samples/audio-wav/audio-wav/build.bat
samples/font/font/build.bat
samples/graphics/graphics/build.bat
samples/hello_world/hello_world/build.bat
samples/input/input/build.bat
samples/library_example/library_example/build.bat
samples/networking/networking/build.bat
samples/pngdec/pngdec/build.bat
samples/pthread/pthread/build.bat
samples/system/system/build.bat

Tested build.bat scripts and got some issues that makes impossible to work. Now looks fine.
Added slashes to correct the concatenation folder strings.
Added @mkdir for target folder %intdir%. Without destination folder created, the rest commands will fail.
In library sample, the last output should be PRX. Fixed.

Updated all build.bat files fixing several issues

---

README.md

Added installation instructions of clang and lld for Arch

Little update on README for Arch users

---

link.x
src/tools/create-eboot/OELFGenDynlibData.go
src/tools/create-eboot/OELFGenProgramHeaders.go
src/tools/create-eboot/PS4Constants.go

Lots of fixes.
For details, see commit messages.

create-lib-testing updates

---

src/crt/build.sh

Fixed Linux crt build script.

---

scripts/autobuild.py

Fixing what appear to be copy/paste errors

Fix copy/paste errors

---

samples/substitute_example/Makefile
samples/substitute_example/substitute_example.sln
samples/substitute_example/substitute_example/build.bat
samples/substitute_example/substitute_example/main.c
samples/substitute_example/substitute_example/substitute.h
samples/substitute_example/substitute_example/substitute_example.vcxproj
samples/substitute_example/substitute_example/substitute_example.vcxproj.filters

Based on library_example by Specter

libsubstitute example

---

link.x
samples/library_example/Makefile

Fix building libraries

---

build/build.sh

Add create-gp4 to build script

---

include/orbis/libkernel.h
include/orbis/libmonovm.h

- Add definitions for libkernel for cpu usage and debug log.
- Add/Update definitions for libmonovm as well as adding some of the mono structures.

Add/Update definitions fo libkernel & libmonovm

---

include/orbis/_types/pad.h

Update ScePad header.

---

include/c++/v1/cmath
include/math.h

Fix functions in math headers.

---

include/orbis/_types/save_data.h

thanks to @nkrapivin for pointing this out

Fix OrbisSaveDataParam definition

---

.github/workflows/toolchain.yml

- Downgrade to LLVM12
Please merge as squash or rebase

CI: fix build 

---

include/orbis/SysCore.h
include/orbis/_types/kernel.h
include/orbis/libkernel.h

Not super useful but can be used to get the appId or titleId of a process.

Add appinfo data type and functions.

---

include/orbis/Net.h
include/orbis/_types/net.h

Defined a few functions & data types I reverse engineered.

Defined some networking functions.

---

.github/workflows/toolchain.yml

Rely less on limited api calls.

CI: Download latest releases from URLs

---

include/orbis/SystemService.h
include/orbis/libkernel.h

Adds some SystemService and Kernel definitions.

add definitions

---

include/orbis/Usbd.h
include/orbis/_types/libusb.h

Adds definitions for the sceUsbd library, similar to libusb.

Add sceUsbd definitions

---

include/orbis/_types/kernel.h
include/orbis/_types/msg_dialog.h

Fix undefined symbols 

---

.github/workflows/toolchain.yml

Also build against llvm 17, 18

Update action versions and rebuild every month

---

include/orbis/_types/kernel.h

The fields are from reverse engineering a bunch of different files, I'm not entirely sure about this, but the fields are roughly like this.

OrbisAppInfo
