- .github/workflows/miralib.yml
- src/tools/miralib/csharp/MiraConnection.cs
This will save you some minutes on your jobs, instead of running this one each time there's a new PR.
Should probably do the same with the other job too, I'll submit another PR for that shortly.
>  Only run miralib job if miralib files change 

- link.x
Align `.got` and `.got.plt` if `.data.rel.ro` doesn't exist.
`create-eboot`/`create-lib` merge `.data.rel.ro`/`.got.plt` into `PT_SCE_RELRO`. Orbis requires `PT_SCE_RELRO` to be page aligned, at least for libs.
> Align .got and .got.plt when needed.

- include/sys/cdefs.h
Previously would cause a redefinition error if you pass `-fgnuc-version=` to >= clang 10.0
> Only define __GNUC__ when undefined.

- samples/font/font/graphics.cpp
- samples/graphics/graphics/graphics.cpp
- samples/pngdec/pngdec/graphics.cpp
- src/crt/build.sh
drawPixel() should always be inlined to increase performance.
added mv command to crt build script.
> Some fixes to samples

- README.md
- extra/macos_pkg_files/post_install_script.sh
- extra/macos_pkg_files/readme.txt
This is a simple PR to fix a typo in the macOS installer messages. (replace `lover` -> `lower`)
thanks for building OpenOrbis! 😄
> Simple typo fix

- src/tools/create-eboot/OELFGenDynlibData.go
`.rela.dyn` entries that refer to symbols contain an index into `.dynsym` as a number. `create-eboot` however adds an additional `SECTION` entry to `.dynsym`, so all the indices get shifted by 1 and relocations begin referencing wrong symbols.
Closes #82 (needs testing)
> Fix (?) GOT index shift

- link.x
- src/tools/create-eboot/OELFGenProgramHeaders.go
This should fix thread-local variable accesses referencing invalid memory. `__tls_get_addr` implementation from musl seems to be compatible enough.
> Generate a proper TLS entry instead of the default empty one

- .github/workflows/docker.yml
- DOCKER.md
- Dockerfile
- To build you must include build-args for GITHUB_REPOSITORY and OO_TOOLCHAIN_VERSION
ex. `--build-arg GITHUB_REPOSITORY=OpenOrbis/OpenOrbis-PS4-Toolchain --build-arg OO_TOOLCHAIN_VERSION=v0.5`
- Workflow automatically handles --build-args
- Workflow will fail because of missing secrets
- Workflow triggers on publishing a release
- Current image size with the v0.5 Toolchain is less than 175 MB when compressed
> Initial Docker commit

- samples/fork_process/.gitignore
- samples/fork_process/Makefile
- samples/fork_process/main.c
- samples/fork_process/mira.c
- samples/fork_process/mira.h
Hey!
I was unsure on how and where to send this. I apologize if this is the wrong approach.
I seems the SYS_exit syscall used by musl causes some kind of deadlock in the ps4 kernel when invoked from a forked process.
Invoking the SceLibcInternal function _Exit() (note the capital E) works fine though. Ideally, _Exit would be dumped, reverse engineered and implemented in musl.
In any case, here is an example that uses mira to obtain sufficient credentials to invoke the SYS_fork syscall, and then terminates the child proc using the _Exit function provided by SceLibcInternal, without causing a kernel deadlock.
> add fork example that does not hang

- .github/workflows/docker.yml
- DOCKER.md
- Dockerfile
- Fixed Typos
- Added Section on build instructions for the Dockerfile
- Removed need for GH repo arg when building Dockerfile
Make sure to squash this pull with the dropdown menu on the merge button. As it's a lot of insignificant changes as testing goes on
> Docker tweaks

- include/orbis/Bgft.h
- include/orbis/_types/bgft.h
All credits to flatz for reverse engineering these, I've fixed the names so they're valid. It is been tested.
Sources:
args: https://github.com/flatz/ps4_stub_lib_maker_v2/blob/master/include/bgft.h
nids: https://github.com/flatz/ps4_stub_lib_maker_v2/blob/master/lib/libSceBgft/libSceBgft.def
real names: https://github.com/idc/ps4libdoc/blob/5.05/system/common/lib/libSceBgft.sprx.json
> Add flatz' bgft prototypes

- include/orbis/Http.h
- include/orbis/NetCtl.h
- include/orbis/_types/ime_dialog.h
- include/orbis/_types/kernel.h
Both `u_short` and `u_int` are used in `_types/kernel.h` but are defined in `sys/types.h` if `sys/types.h` is not included elsewhere first it will cause a compilation error
> Fix various header issues

- src/tools/create-eboot/OELFGenDynlibData.go
Output which symbol was not able to be found.
> Fix missing symbol name when not found

- include/sys/ioctl.h
the new signature is covered by a PS4 ifdef so should be safe.
musl PR incoming
> Fix issue #132 by using FreeBSD ioctl signature.

- include/orbis/SaveData.h
This fixes an issue where including SaveData.h multiple times causes compilation to fail.
> Fix SaveData.h compiling error

- Dockerfile
Ubuntu does not keep older versions of their packages on their repos
> Remove specific versioning from Dockerfile

- link.x
Fixes compilers that use `--gc-sections` (RustC)
> Force sce sections to appear in the elf.

- include/orbis/SystemService.h
A follow up of #230, as mentioned by @sleirsgoevy :
> definitions should be (void), because in C (as opposed to C++) () means (...), i.e. arbitrary number of arbitrary arguments
I have also fixed the `#endif` order for C++ users.
> Fix C definitions

- include/orbis/GnmDriver.h
- include/orbis/_types/gnm.h
- include/orbis/_types/video.h
The GnmDriver definitions may be used by a program or library to setup GNM (draw) command buffers and submit them.
The VideoOut definitions are meant to be used with `sceVideoOutSetBufferAttribute` since tiling mode and aspect ratio are arguments to it.
> Add some definitions for GnmDriver and VideoOut

- include/orbis/Pad.h
- include/orbis/_types/pad.h
Adds functions and structures used to connect to extension controllers (guitars, drums etc) as used in GHLive and RB4.
* scePadOpenExt appears to be used for connecting an extension controller with a provided VID/PID (but maybe this isn't required or maybe scePadOpen also accepts that data?)
* scePadReadState returns identical output to scePadRead, just without the "count" parameter.
* scePadOutputReport is used to send a USB control request to the controller. This is required to get outputs from the GHLive dongle.
* scePadGetControllerInformation returns touchpad/stick data, whether remote play is being used, and the class of the device. (the class is used by those two games to determine the instrument)
* scePadGetExtControllerInformation is seemingly identical.
> Add extension controller support to Pad.h header.

- include/orbis/_types/save_data.h
Use `time.h` for `time_t` to better align with common coding practice.
> Change sys/time.h to time.h in save_data.h

- include/orbis/GnmDriver.h
- include/orbis/_types/gnm.h
Also added comments describing the required number of DWORDs used by commands.
> GnmDriver: Add definitions for SetEmbeddedShader and DrawIndexAuto

- samples/library_example/Makefile
- samples/library_example/library_example/lib.stub.c
Build was failing because lib.cpp in the library_example has a bunch of external dependencies. For building the *.stub files, the implementation doesn't matter, only having the right symbols matters (its sorta like a header but in a .so) Added a .stub.c file with the same testLibraryFunction and a empty impl.
this fixes the build being broken on master
> build library stub from separate file

- include/orbis/_types/kernel.h
clang version 18.1.6 (Win 10 x86_64)
Compiled test:
[stat_test.zip](https://github.com/user-attachments/files/21342654/stat_test.zip)
> Fix mode_t for OrbisKernelStat
